### PR TITLE
Add options for setting OUTFILE, OUTFILE_PREFIX, OUTDIR, and OUTPUT

### PR DESCRIPTION
**Pull request by weslambert**
This PR provides the ability to set custom values for the `OUTFILE` and `OUTPUT` variables (while leaving the previous defaults as-is if nothing else is specified), and also adds two new variables:

`OUTFILE_PREFIX` - Allows for replacement of `catscale_` with something else for the final tar file prefix.
`OUTDIR`: Allows for replacing `catscale_out` with something else to act as the directory where files will be transferred before creating the final tar file.

Example of running with new/updated variables:

`sudo OUTPUT=/tmp OUTDIR=mynewoutputdirname OUTFILE_PREFIX=cs_ OUTFILE=blahblah ./Cat-Scale.sh`

### CODE REVIEW

**Comment by weslambert** [comment]
@arthomas @56616c6f72 , any thoughts on this? Or would it be more preferred to pass options like `--option1 blah`?

**Comment by 56616c6f72** [comment]
Hey Wes! 

Sorry about the delay! I realize my notifications could have been setup a little better. Won't happen again :) 

We actually spoke about such feature internally long ago, but never got around implementing. Thanks for taking the initiative to get this started.  We created the tool to be as simple as possible so even a junior admin could run it without any parameters. But certainly as the tool goes public, it should also accommodate such customizations. 

Ideally we want the options to be passed as options similar to you have highlighted. If not options set it should use defaults as you highlighted. 

Would you be able to change your implementation to reflect this?

**Comment by weslambert** [comment]
> Hey Wes!
> 
> Sorry about the delay! I realize my notifications could have been setup a little better. Won't happen again :)
> 
> We actually spoke about such feature internally long ago, but never got around implementing. Thanks for taking the initiative to get this started. We created the tool to be as simple as possible so even a junior admin could run it without any parameters. But certainly as the tool goes public, it should also accommodate such customizations.
> 
> Ideally we want the options to be passed as options similar to you have highlighted. If not options set it should use defaults as you highlighted.
> 
> Would you be able to change your implementation to reflect this?

No worries! Sounds good! I'll work on that and alter the PR accordingly 👍

**Comment by weslambert** [comment]
Updated.  I considered just having `OUTDIR`, as opposed to `OUTROOT` and `OUTDIR` (root + subdir), but didn't want to mess with the original script too much. Let me know if you would like me to adjust anything.  Thanks!

**Comment by 56616c6f72** [comment]
Looking beautiful. Works nicely on Solaris also. For mergng OUTROOT and OUTDIR. Let's not remove features that already exist for now. This just provides more flexibility as is. 

Some changes to help print(code below):
- updated to include the options in descriptions
- changed ex to true default values
- reorder to match description order to usage order
- added sudo to usage. just to make it fool proof.

What do you think?

```
Usage: sudo $0 [-d OUTDIR ] [-f OUTFILE ] [ -o OUTROOT ] [-p OUTFILE_PREFIX ]

 -d	OUTDIR, Optional, Directory where output will be staged while running CatScale. Overwrites default, which is "catscale_out" 
 -f	OUTFILE, Optional, Name of resultant archive file created by CatScale (.tar.gz will be appended by the script). Overwrites default, which is "catscale_$(hostname -s)-$date +"%Y%m%d-%H%M")"
 -o	OUTROOT, Optional, Root directory/filesystem for output to be saved. Overwrites default, which is "$(pwd)" 
 -p	OUTFILE_PREFIX, Optional, Prefix to use for archive file. Overwrites default, which is "catscale_"
```

**Comment by weslambert** [comment]
Great suggestions, thanks! This has been updated.

**Comment by 56616c6f72** [comment]
I noticed on Solaris there are some weird behavior with using $(hostname) in help. I will fix these to something more simple after merge.

Thanks! :)

**Pull request merged**
